const POSTS_DATA = [
  { id: 1, image: "https://picsum.photos/seed/post1/400/240", featured: true, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av1/32/32", verified: true },
  { id: 2, image: "https://picsum.photos/seed/post2/400/240", featured: true, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av2/32/32", verified: false },
  { id: 3, image: "https://picsum.photos/seed/post3/400/240", featured: true, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av3/32/32", verified: true },
  { id: 4, image: "https://picsum.photos/seed/post4/400/240", featured: false, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av4/32/32", verified: true },
  { id: 5, image: "https://picsum.photos/seed/post5/400/240", featured: false, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av5/32/32", verified: false },
  { id: 6, image: "https://picsum.photos/seed/post6/400/240", featured: false, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av6/32/32", verified: true },
  { id: 7, image: "https://picsum.photos/seed/post7/400/240", featured: false, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av7/32/32", verified: false },
  { id: 8, image: "https://picsum.photos/seed/post8/400/240", featured: false, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av8/32/32", verified: false },
  { id: 9, image: "https://picsum.photos/seed/post9/400/240", featured: false, text: "dummy text of the printing and typesetting industds has been the industry's dummy text....", area: "Local Area, District", date: "30 Mar 26", author: "Member name", avatar: "https://picsum.photos/seed/av9/32/32", verified: false },
];
